import Head from "next/head";
import { Inter } from "next/font/google";
import { Button, ButtonGroup, Heading, Text } from "@chakra-ui/react";
import {
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  Box,
  TabBar,
} from "@chakra-ui/react";
import { CircularProgress, CircularProgressLabel } from "@chakra-ui/react";
import { CheckIcon, WarningIcon } from "@chakra-ui/icons";
import {
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionPanel,
  AccordionIcon,
} from "@chakra-ui/react";
import {
  List,
  ListItem,
  ListIcon,
  OrderedList,
  UnorderedList,
} from "@chakra-ui/react";
import NavBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function AssignmentPage() {
  let home = false;
  let assign = true;
  return (
    <>
      <Head>
        <title>Split || Assignments</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar page="assignments" />
        <Card margin={10} bg="brand.100">
          <Accordion defaultIndex={[0]} allowMultiple>
            <AccordionItem>
              <h2>
                <AccordionButton>
                  <Box as="span" flex="1" textAlign="left">
                    CAL Essay Due 4/13
                  </Box>
                  <AccordionIcon />
                </AccordionButton>
              </h2>
              <AccordionPanel pb={4}>
                <CircularProgress value={40} color="green.400">
                  <CircularProgressLabel>40%</CircularProgressLabel>
                </CircularProgress>
                <List spacing={3}>
                  <ListItem>
                    <ListIcon as={CheckIcon} color="green.500" />
                    Outline
                  </ListItem>
                  <ListItem>
                    <ListIcon as={CheckIcon} color="green.500" />
                    Introduction
                  </ListItem>
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Body Parargaphs One and Two
                  </ListItem>
                  {/* You can also use custom icons from react-icons */}
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Last Body Paragraph and Conclusion
                  </ListItem>
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Revision and Submit
                  </ListItem>
                </List>
              </AccordionPanel>
            </AccordionItem>

            <AccordionItem>
              <h2>
                <AccordionButton>
                  <Box as="span" flex="1" textAlign="left">
                    Math Homework
                  </Box>
                  <AccordionIcon />
                </AccordionButton>
              </h2>
              <AccordionPanel pb={4}>
                <List spacing={3}>
                  <CircularProgress value={50} color="green.400">
                    <CircularProgressLabel>50%</CircularProgressLabel>
                  </CircularProgress>
                  <ListItem>
                    <ListIcon as={CheckIcon} color="green.500" />
                    Problems 1 to 5
                  </ListItem>
                  <ListItem>
                    <ListIcon as={CheckIcon} color="green.500" />
                    Problems 5 to 10
                  </ListItem>
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Problems 10 to 15
                  </ListItem>
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Problems 15 to 20
                  </ListItem>
                </List>
              </AccordionPanel>
            </AccordionItem>

            <AccordionItem>
              <h2>
                <AccordionButton>
                  <Box as="span" flex="1" textAlign="left">
                    Study for Physics Midterm!
                  </Box>
                  <AccordionIcon />
                </AccordionButton>
              </h2>
              <AccordionPanel pb={4}>
                <List spacing={3}>
                  <CircularProgress value={20} color="green.400">
                    <CircularProgressLabel>20%</CircularProgressLabel>
                  </CircularProgress>
                  <ListItem>
                    <ListIcon as={CheckIcon} color="green.500" />
                    Read Textbook Chapters 1 and 2
                  </ListItem>
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Exersize Problems for Chapter 1 and 2
                  </ListItem>
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Read Textbook Chapters 3 and 4
                  </ListItem>
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Exersize Problems for Chapter 3 and 4
                  </ListItem>
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Practice Exam
                  </ListItem>
                  <ListItem>
                    <ListIcon as={WarningIcon} color="yellow.500" />
                    Go over Exam + review gaps in understanding
                  </ListItem>
                </List>
              </AccordionPanel>
            </AccordionItem>
          </Accordion>
        </Card>
      </main>
    </>
  );
}
