import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Button, Center, ChakraProvider, Heading, Menu, MenuButton, MenuItem, MenuList, Portal } from '@chakra-ui/react'
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  return (
    <>
      <Head>
        <title>Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center>
          <Heading size={'4xl'} color={'purple'}>Functioner</Heading>
        </Center>
      </main>
    </>
  )
}
